# -*- coding: utf-8 -*-
import json
from pathlib import Path

out = Path("/workspace/xinglin-mowen/logic")

pack = {
    "id": "xinglin-mowen-slice-logic",
    "version": 1,
    "project": "杏林墨问",
    "scope": "vertical_slice",
    "notes": {
        "not_quiz": True,
        "no_unique_answer": True,
        "proficiency_this_slice": "interface_only",
        "player_never_shown_diagnosis_name": True,
        "input": "pulse is visual, herbs are dragged, points are tapped; no menu-select treatment",
    },
    "exam_ids": ["wang", "wen_listen", "wen_ask", "qie"],
    "exam_labels": {
        "wang": {"zh": "望", "en": "Look", "ja": "望"},
        "wen_listen": {"zh": "闻", "en": "Listen", "ja": "聞"},
        "wen_ask": {"zh": "问", "en": "Ask", "ja": "問"},
        "qie": {"zh": "切", "en": "Pulse", "ja": "切"},
    },
}

# --- four exam FSM ---
fsm = {
    "id": "four_exam_fsm",
    "initial": "clinic_idle",
    "flags_on_patient": {
        "wang": False,
        "wen_listen": False,
        "wen_ask": False,
        "qie": False,
    },
    "states": {
        "clinic_idle": {
            "enter": "show clinic, wait for player to pick a patient",
            "actions": {"select_patient": "patient_selected"},
        },
        "patient_selected": {
            "enter": "seat patient; no symptoms dumped; four exam buttons + treat available",
            "actions": {
                "do_wang": "examining",
                "do_wen_listen": "examining",
                "do_wen_ask": "examining",
                "do_qie": "examining",
                "open_treatment": "treatment_choice",
                "dismiss_patient": "clinic_idle",
            },
        },
        "examining": {
            "enter": "play the chosen exam; set its flag true; reveal only that exam's clues",
            "note": "exams are any order, repeatable (replay does not re-penalize)",
            "actions": {
                "do_wang": "examining",
                "do_wen_listen": "examining",
                "do_wen_ask": "examining",
                "do_qie": "examining",
                "open_treatment": "treatment_choice",
                "back": "patient_selected",
            },
        },
        "treatment_choice": {
            "enter": "choose formula plate or acupuncture; allowed even if flags incomplete",
            "actions": {
                "choose_formula": "formula_crafting",
                "choose_acupuncture": "needling",
                "back_to_exam": "examining",
            },
        },
        "formula_crafting": {
            "enter": "drag herbs onto plate (3-8). not a dropdown of named formulas",
            "actions": {
                "confirm_formula": "settling",
                "back": "treatment_choice",
            },
        },
        "needling": {
            "enter": "tap 2-5 points on body diagram. not a menu",
            "actions": {
                "confirm_needling": "settling",
                "back": "treatment_choice",
            },
        },
        "settling": {
            "enter": "run scoring.json; show rank + process + over/mis flags; never print diagnosis id",
            "actions": {"next_patient": "clinic_idle"},
        },
    },
    "rules": {
        "can_treat_with_missing_exams": True,
        "exam_order": "any",
        "repeat_exam_ok": True,
        "clues_never_auto_complete": True,
        "treat_from_patient_selected_ok": True,
    },
}

# --- herbs (draggable inventory) ---
herbs = [
    {"id": "mahuang", "zh": "麻黄", "en": "Ephedra", "ja": "麻黄",
     "nature": "warm", "flavor": ["pungent", "bitter"], "direction": "float",
     "actions": ["release_exterior", "induce_sweat", "move_lung_qi"],
     "zheng_cost": 2, "onset": "fast"},
    {"id": "guizhi", "zh": "桂枝", "en": "Cinnamon twig", "ja": "桂枝",
     "nature": "warm", "flavor": ["pungent", "sweet"], "direction": "float",
     "actions": ["release_exterior", "warm_yang", "harmonize_ying_wei"],
     "zheng_cost": 1, "onset": "medium"},
    {"id": "xingren", "zh": "杏仁", "en": "Apricot kernel", "ja": "杏仁",
     "nature": "slightly_warm", "flavor": ["bitter"], "direction": "down",
     "actions": ["down_qi", "stop_cough"],
     "zheng_cost": 0, "onset": "medium"},
    {"id": "gancao", "zh": "甘草", "en": "Licorice", "ja": "甘草",
     "nature": "neutral", "flavor": ["sweet"], "direction": "none",
     "actions": ["harmonize", "tonify_qi"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "shengjiang", "zh": "生姜", "en": "Fresh ginger", "ja": "生姜",
     "nature": "warm", "flavor": ["pungent"], "direction": "float",
     "actions": ["release_exterior", "warm_middle", "stop_vomit"],
     "zheng_cost": 1, "onset": "fast"},
    {"id": "dazao", "zh": "大枣", "en": "Jujube", "ja": "大棗",
     "nature": "warm", "flavor": ["sweet"], "direction": "none",
     "actions": ["tonify_qi", "nourish_blood", "harmonize"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "baishao", "zh": "白芍", "en": "White peony", "ja": "白芍",
     "nature": "cool", "flavor": ["bitter", "sour"], "direction": "none",
     "actions": ["nourish_blood", "soften_liver", "astringe_yin"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "chaihu", "zh": "柴胡", "en": "Bupleurum", "ja": "柴胡",
     "nature": "cool", "flavor": ["pungent", "bitter"], "direction": "lift",
     "actions": ["soothe_liver", "move_qi", "release_shaoyang"],
     "zheng_cost": 1, "onset": "medium"},
    {"id": "danggui", "zh": "当归", "en": "Angelica", "ja": "当帰",
     "nature": "warm", "flavor": ["sweet", "pungent"], "direction": "none",
     "actions": ["nourish_blood", "move_blood"],
     "zheng_cost": 0, "onset": "medium"},
    {"id": "baizhu", "zh": "白术", "en": "Atractylodes", "ja": "白朮",
     "nature": "warm", "flavor": ["sweet", "bitter"], "direction": "none",
     "actions": ["tonify_qi", "dry_damp", "tonify_spleen"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "fuling", "zh": "茯苓", "en": "Poria", "ja": "茯苓",
     "nature": "neutral", "flavor": ["sweet", "bland"], "direction": "down",
     "actions": ["drain_damp", "tonify_spleen", "calm_shen"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "bohe", "zh": "薄荷", "en": "Mint", "ja": "薄荷",
     "nature": "cool", "flavor": ["pungent"], "direction": "float",
     "actions": ["release_exterior", "soothe_liver", "clear_head"],
     "zheng_cost": 0, "onset": "fast"},
    {"id": "zhiqiao", "zh": "枳壳", "en": "Bitter orange", "ja": "枳殻",
     "nature": "slightly_cold", "flavor": ["bitter", "sour"], "direction": "down",
     "actions": ["move_qi", "open_chest"],
     "zheng_cost": 1, "onset": "fast"},
    {"id": "xiangfu", "zh": "香附", "en": "Cyperus", "ja": "香附",
     "nature": "neutral", "flavor": ["pungent", "bitter", "sweet"], "direction": "none",
     "actions": ["soothe_liver", "move_qi"],
     "zheng_cost": 1, "onset": "medium"},
    {"id": "shudi", "zh": "熟地", "en": "Prepared rehmannia", "ja": "熟地",
     "nature": "slightly_warm", "flavor": ["sweet"], "direction": "none",
     "actions": ["nourish_yin", "nourish_blood"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "shanyao", "zh": "山药", "en": "Dioscorea", "ja": "山薬",
     "nature": "neutral", "flavor": ["sweet"], "direction": "none",
     "actions": ["tonify_qi", "nourish_yin", "tonify_spleen"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "shanzhuyu", "zh": "山茱萸", "en": "Cornus", "ja": "山茱萸",
     "nature": "slightly_warm", "flavor": ["sour"], "direction": "none",
     "actions": ["nourish_yin", "astringe", "tonify_kidney"],
     "zheng_cost": 0, "onset": "slow"},
    {"id": "mudanpi", "zh": "牡丹皮", "en": "Moutan", "ja": "牡丹皮",
     "nature": "slightly_cold", "flavor": ["bitter", "pungent"], "direction": "none",
     "actions": ["cool_blood", "clear_deficiency_heat"],
     "zheng_cost": 1, "onset": "medium"},
    {"id": "zexie", "zh": "泽泻", "en": "Alisma", "ja": "沢瀉",
     "nature": "cold", "flavor": ["sweet", "bland"], "direction": "down",
     "actions": ["drain_damp"],
     "zheng_cost": 0, "onset": "medium"},
    {"id": "zhimu", "zh": "知母", "en": "Anemarrhena", "ja": "知母",
     "nature": "cold", "flavor": ["bitter", "sweet"], "direction": "none",
     "actions": ["nourish_yin", "clear_heat", "clear_deficiency_heat"],
     "zheng_cost": 1, "onset": "medium"},
    {"id": "huangbai", "zh": "黄柏", "en": "Phellodendron", "ja": "黄柏",
     "nature": "cold", "flavor": ["bitter"], "direction": "down",
     "actions": ["clear_heat", "clear_deficiency_heat", "dry_damp"],
     "zheng_cost": 2, "onset": "fast"},
    {"id": "jinyinhua", "zh": "金银花", "en": "Honeysuckle", "ja": "金銀花",
     "nature": "cold", "flavor": ["sweet"], "direction": "float",
     "actions": ["clear_heat", "resolve_toxin", "release_exterior"],
     "zheng_cost": 1, "onset": "fast"},
    {"id": "lianqiao", "zh": "连翘", "en": "Forsythia", "ja": "連翹",
     "nature": "slightly_cold", "flavor": ["bitter"], "direction": "float",
     "actions": ["clear_heat", "resolve_toxin"],
     "zheng_cost": 1, "onset": "fast"},
    {"id": "fuzi", "zh": "附子", "en": "Aconite", "ja": "附子",
     "nature": "hot", "flavor": ["pungent"], "direction": "none",
     "actions": ["restore_yang", "warm_interior", "warm_yang"],
     "zheng_cost": 3, "onset": "fast"},
    {"id": "ganjiang", "zh": "干姜", "en": "Dried ginger", "ja": "乾姜",
     "nature": "hot", "flavor": ["pungent"], "direction": "none",
     "actions": ["warm_interior", "warm_middle", "warm_yang"],
     "zheng_cost": 2, "onset": "fast"},
]

# --- acupoints (tappable) ---
acupoints = [
    {"id": "fengchi", "zh": "风池", "en": "Fengchi", "ja": "風池", "region": "nape",
     "actions": ["release_exterior", "expel_wind", "clear_head"]},
    {"id": "hegu", "zh": "合谷", "en": "Hegu", "ja": "合谷", "region": "hand",
     "actions": ["release_exterior", "move_qi", "clear_head"]},
    {"id": "lieque", "zh": "列缺", "en": "Lieque", "ja": "列缺", "region": "wrist",
     "actions": ["release_exterior", "move_lung_qi"]},
    {"id": "dazhui", "zh": "大椎", "en": "Dazhui", "ja": "大椎", "region": "upper_back",
     "actions": ["release_exterior", "expel_wind", "warm_yang"]},
    {"id": "taichong", "zh": "太冲", "en": "Taichong", "ja": "太衝", "region": "foot",
     "actions": ["soothe_liver", "move_qi", "descend_yang"]},
    {"id": "qimen", "zh": "期门", "en": "Qimen", "ja": "期門", "region": "flank",
     "actions": ["soothe_liver", "move_qi"]},
    {"id": "neiguan", "zh": "内关", "en": "Neiguan", "ja": "内関", "region": "forearm",
     "actions": ["open_chest", "calm_shen", "move_qi"]},
    {"id": "yanglingquan", "zh": "阳陵泉", "en": "Yanglingquan", "ja": "陽陵泉", "region": "leg",
     "actions": ["soothe_liver", "move_qi"]},
    {"id": "zusanli", "zh": "足三里", "en": "Zusanli", "ja": "足三里", "region": "leg",
     "actions": ["tonify_qi", "tonify_spleen", "harmonize"]},
    {"id": "taixi", "zh": "太溪", "en": "Taixi", "ja": "太渓", "region": "ankle",
     "actions": ["nourish_yin", "tonify_kidney"]},
    {"id": "sanyinjiao", "zh": "三阴交", "en": "Sanyinjiao", "ja": "三陰交", "region": "leg",
     "actions": ["nourish_yin", "nourish_blood", "tonify_spleen"]},
    {"id": "shenshu", "zh": "肾俞", "en": "Shenshu", "ja": "腎兪", "region": "low_back",
     "actions": ["tonify_kidney", "nourish_yin"]},
    {"id": "yongquan", "zh": "涌泉", "en": "Yongquan", "ja": "湧泉", "region": "sole",
     "actions": ["nourish_yin", "descend_fire"]},
    {"id": "zhaohai", "zh": "照海", "en": "Zhaohai", "ja": "照海", "region": "ankle",
     "actions": ["nourish_yin", "clear_deficiency_heat"]},
    {"id": "quchi", "zh": "曲池", "en": "Quchi", "ja": "曲池", "region": "elbow",
     "actions": ["clear_heat", "release_exterior"]},
    {"id": "mingmen", "zh": "命门", "en": "Mingmen", "ja": "命門", "region": "low_back",
     "actions": ["warm_yang", "warm_interior"]},
]

# --- 3 pathogenesis ---
cases = [
    {
        "id": "fenghan_biao",
        "internal_name_zh": "风寒束表",
        "bind_character_id": "char_porter",
        "urgency": "medium",
        "zheng_qi": 0.7,
        "primary_exams": ["qie", "wang"],
        "pulse": {
            "id": "fu_jin",
            "zh": "浮紧",
            "en": "floating-tight",
            "ja": "浮緊",
            "rate_bpm": 68,
            "visual": {
                "depth": 0.15,
                "amplitude": 0.85,
                "tension": 0.9,
                "width": 0.45,
                "smoothness": 0.2,
                "note_for_art": "浅层、绷紧、少弹性。Steam 截图用：墨线贴着宣纸表层走，不要沉下去。",
            },
        },
        "required_actions": ["release_exterior"],
        "preferred_actions": ["induce_sweat", "move_lung_qi", "warm_yang", "harmonize_ying_wei"],
        "preferred_natures": ["warm", "slightly_warm"],
        "forbidden_actions": ["clear_heat", "resolve_toxin", "nourish_yin", "clear_deficiency_heat"],
        "over_treat_actions": ["induce_sweat"],
        "over_treat_zheng_cost": 5,
        "clues": {
            "wang": {
                "unlocks": ["face_pale", "huddled", "tongue_thin_white"],
                "zh": ["脸色偏白，肩往里收", "舌淡，苔薄白"],
                "en": ["pale, shoulders drawn in", "pale tongue, thin white coat"],
                "ja": ["顔色が白い、肩が内側へ", "舌淡、苔薄白"],
            },
            "wen_listen": {
                "unlocks": ["heavy_voice", "slight_nasal"],
                "zh": ["说话闷，鼻音一点点", "身上没有明显热气"],
                "en": ["voice sounds stuffed, slight nasal", "no heat coming off the body"],
                "ja": ["声がこもる、鼻声気味", "熱気は感じない"],
            },
            "wen_ask": {
                "unlocks": ["chills_gt_fever", "no_sweat", "body_ache", "clear_snot"],
                "inquiry_anchor": [
                    "怕冷比发热明显",
                    "身上酸疼",
                    "汗出不来",
                    "鼻涕清",
                    "这两天刚受了风",
                ],
                "never_say": ["风寒", "风寒束表", "外感风寒", "麻黄汤", "桂枝汤", "感冒风寒"],
            },
            "qie": {
                "unlocks": ["pulse_fu_jin"],
                "zh": ["脉在浅层，绷着，不滑"],
                "en": ["pulse sits high, taut, not slippery"],
                "ja": ["脈は浅く、張って滑らない"],
            },
        },
        "legal_formula_examples": [
            {"herbs": ["mahuang", "guizhi", "xingren", "gancao"], "onset": "fast", "note": "发表力强，见效快，耗正多"},
            {"herbs": ["guizhi", "baishao", "shengjiang", "dazao", "gancao"], "onset": "medium", "note": "解表兼和营，慢一点但更稳"},
        ],
        "legal_point_examples": [
            {"points": ["fengchi", "hegu", "lieque"], "onset": "fast"},
            {"points": ["fengchi", "hegu", "dazhui", "zusanli"], "onset": "medium", "note": "加足三里护正，稍慢"},
        ],
        "common_mistreat": [
            {"herbs": ["jinyinhua", "lianqiao"], "why": "当热邪清，表寒更闭"},
            {"points": ["quchi"], "why": "清气分开，解表不够"},
        ],
        "settlement_flavor": {
            "good": {"zh": "寒从体表散开，人松下来了。", "en": "The chill lets go at the surface.", "ja": "冷えが表からほどけた。"},
            "slow": {"zh": "寒在松，只是慢。", "en": "It's easing, just slowly.", "ja": "寒さは緩むが遅い。"},
            "over": {"zh": "表开得太狠，人有点空。", "en": "The exterior opened too hard; they feel emptied.", "ja": "表を開きすぎて、空になった。"},
            "mis": {"zh": "药往热上走，怕冷反而更明显。", "en": "The herbs ran toward heat; the chills worsened.", "ja": "薬が熱に向かい、悪寒が強まった。"},
        },
    },
    {
        "id": "ganyu_qizhi",
        "internal_name_zh": "肝郁气滞",
        "bind_character_id": "char_clerk",
        "urgency": "low",
        "zheng_qi": 0.75,
        "primary_exams": ["wen_ask", "qie"],
        "pulse": {
            "id": "xian",
            "zh": "弦",
            "en": "wiry",
            "ja": "弦",
            "rate_bpm": 72,
            "visual": {
                "depth": 0.45,
                "amplitude": 0.7,
                "tension": 1.0,
                "width": 0.35,
                "smoothness": 0.1,
                "note_for_art": "如按琴弦，长、直、弹手。截图用：一条绷直的墨线，不要圆润波。",
            },
        },
        "required_actions": ["soothe_liver", "move_qi"],
        "preferred_actions": ["nourish_blood", "tonify_spleen", "open_chest", "soften_liver"],
        "preferred_natures": ["cool", "neutral", "slightly_cold"],
        "forbidden_actions": ["induce_sweat", "restore_yang", "warm_interior"],
        "over_treat_actions": ["move_qi"],
        "over_treat_zheng_cost": 6,
        "clues": {
            "wang": {
                "unlocks": ["dusky_face", "sigh_posture", "tongue_thin_white"],
                "zh": ["脸色滞，像叹着气坐着", "舌边略红，苔薄"],
                "en": ["dull complexion, sitting as if mid-sigh", "slightly red tongue edges, thin coat"],
                "ja": ["顔色が滞り、溜息の姿勢", "舌辺がやや赤、苔薄"],
            },
            "wen_listen": {
                "unlocks": ["long_sighs", "tight_voice"],
                "zh": ["说话前先出一口长气", "胸口气不顺"],
                "en": ["a long breath before speaking", "voice sits tight in the chest"],
                "ja": ["話す前に長い息", "胸で声がつかえる"],
            },
            "wen_ask": {
                "unlocks": ["chest_flank_tight", "better_after_sigh", "poor_appetite", "sleep_light"],
                "inquiry_anchor": [
                    "胸口或两胁发闷",
                    "叹口气会好一点",
                    "吃不下多少",
                    "睡不实",
                    "最近心里不顺",
                ],
                "never_say": ["肝郁", "肝气", "肝郁气滞", "逍遥散", "四逆散", "郁证"],
            },
            "qie": {
                "unlocks": ["pulse_xian"],
                "zh": ["脉直而长，按上去像弦"],
                "en": ["pulse feels straight and long, like a string"],
                "ja": ["脈がまっすぐ長く、弦のよう"],
            },
        },
        "legal_formula_examples": [
            {"herbs": ["chaihu", "baishao", "danggui", "baizhu", "fuling", "bohe", "gancao"], "onset": "medium", "note": "疏肝兼养血健脾，稳"},
            {"herbs": ["chaihu", "zhiqiao", "baishao", "gancao"], "onset": "fast", "note": "行气更快，养血少"},
        ],
        "legal_point_examples": [
            {"points": ["taichong", "qimen", "neiguan"], "onset": "fast"},
            {"points": ["taichong", "qimen", "yanglingquan", "zusanli"], "onset": "medium"},
        ],
        "common_mistreat": [
            {"herbs": ["mahuang", "guizhi"], "why": "当表证发汗，气更乱"},
            {"herbs": ["shudi", "huangbai"], "why": "滋腻或苦寒压气，闷更重"},
            {"points": ["mingmen"], "why": "温阳不疏肝"},
        ],
        "settlement_flavor": {
            "good": {"zh": "气散开了，胸口松一截。", "en": "The qi unknots; the chest has room.", "ja": "気がほどけ、胸が開く。"},
            "slow": {"zh": "闷在退，还要几天。", "en": "The tightness is backing off, over days.", "ja": "滞りは退くが日が要る。"},
            "over": {"zh": "气走得太猛，人反而发虚。", "en": "Qi moved too hard; they feel hollow.", "ja": "気を動かしすぎて虚になった。"},
            "mis": {"zh": "药没走到胁上，闷还在。", "en": "The herbs never reached the flanks; the tightness stays.", "ja": "薬が脇に届かず、悶えたまま。"},
        },
    },
    {
        "id": "yinxu_neire",
        "internal_name_zh": "阴虚内热",
        "bind_character_id": "char_copyist",
        "urgency": "medium",
        "zheng_qi": 0.45,
        "primary_exams": ["qie", "wang"],
        "pulse": {
            "id": "xi_shu",
            "zh": "细数",
            "en": "thin-rapid",
            "ja": "細数",
            "rate_bpm": 92,
            "visual": {
                "depth": 0.55,
                "amplitude": 0.28,
                "tension": 0.4,
                "width": 0.22,
                "smoothness": 0.55,
                "note_for_art": "线细、跳得快、力度弱。截图用：细墨线密点，不要粗、不要浮在表层。",
            },
        },
        "required_actions": ["nourish_yin"],
        "preferred_actions": ["clear_deficiency_heat", "nourish_blood", "tonify_kidney"],
        "preferred_natures": ["slightly_cold", "cold", "neutral", "slightly_warm"],
        "forbidden_actions": ["restore_yang", "warm_interior", "induce_sweat", "warm_yang"],
        "over_treat_actions": ["clear_heat", "clear_deficiency_heat"],
        "over_treat_zheng_cost": 4,
        "clues": {
            "wang": {
                "unlocks": ["malar_flush", "thin_body", "tongue_red_little_coat"],
                "zh": ["两颧发红，人偏瘦", "舌红少苔"],
                "en": ["flushed cheekbones, thinner frame", "red tongue, little coat"],
                "ja": ["両頬が赤い、痩せ気味", "舌紅、苔が少ない"],
            },
            "wen_listen": {
                "unlocks": ["dry_weak_voice", "night_restless"],
                "zh": ["声音干、力气不大", "夜里安稳不了"],
                "en": ["voice dry and thin", "nights are not quiet"],
                "ja": ["声が乾いて弱い", "夜が落ち着かない"],
            },
            "wen_ask": {
                "unlocks": ["heat_in_palms", "night_sweat", "dry_throat", "insomnia"],
                "inquiry_anchor": [
                    "手心脚心热",
                    "夜里出汗",
                    "喉咙干",
                    "睡不着或易醒",
                    "下午更烦",
                ],
                "never_say": ["阴虚", "阴虚火旺", "阴虚内热", "六味地黄", "知柏地黄", "虚火"],
            },
            "qie": {
                "unlocks": ["pulse_xi_shu"],
                "zh": ["脉细，跳得偏快"],
                "en": ["pulse is thin and a bit fast"],
                "ja": ["脈が細く、やや速い"],
            },
        },
        "legal_formula_examples": [
            {"herbs": ["shudi", "shanyao", "shanzhuyu", "mudanpi", "zexie", "fuling"], "onset": "slow", "note": "滋阴为主，稳，见效慢"},
            {"herbs": ["shudi", "shanyao", "shanzhuyu", "mudanpi", "zexie", "fuling", "zhimu", "huangbai"], "onset": "medium", "note": "兼清虚热，稍快，苦寒多了会过治"},
        ],
        "legal_point_examples": [
            {"points": ["taixi", "sanyinjiao", "shenshu"], "onset": "slow"},
            {"points": ["taixi", "sanyinjiao", "yongquan", "zhaohai"], "onset": "medium"},
        ],
        "common_mistreat": [
            {"herbs": ["fuzi", "ganjiang"], "why": "温阳助热，虚火更旺"},
            {"herbs": ["mahuang"], "why": "发汗伤阴"},
            {"points": ["mingmen", "dazhui"], "why": "温阳不滋阴"},
        ],
        "settlement_flavor": {
            "good": {"zh": "那点虚火往下收，夜里能静一些。", "en": "The false heat settles; nights get quieter.", "ja": "虚火が下り、夜が静かに。"},
            "slow": {"zh": "阴在补，火还要慢慢退。", "en": "Yin is filling; the heat will take days.", "ja": "陰は補えるが、火は日が要る。"},
            "over": {"zh": "苦寒用多了，胃先受不住。", "en": "Too much bitter-cold; the stomach folds first.", "ja": "苦寒が過ぎ、胃が先に参った。"},
            "mis": {"zh": "越温越燥，夜里更不安。", "en": "The more it was warmed, the drier the nights.", "ja": "温めるほど燥き、夜が荒れる。"},
        },
    },
]

# --- scoring ---
scoring = {
    "id": "efficacy_scoring",
    "no_unique_answer": True,
    "player_facing_ranks": [
        {"id": "none", "min": 0.0, "max": 0.15, "zh": "未效", "en": "No effect", "ja": "効かず"},
        {"id": "slight", "min": 0.15, "max": 0.35, "zh": "小效", "en": "Slight", "ja": "わずかに"},
        {"id": "work", "min": 0.35, "max": 0.55, "zh": "见效", "en": "Working", "ja": "効き始め"},
        {"id": "clear", "min": 0.55, "max": 0.75, "zh": "显效", "en": "Clear effect", "ja": "明らかに"},
        {"id": "toward_heal", "min": 0.75, "max": 1.01, "zh": "向愈", "en": "Turning toward health", "ja": "快方へ"},
    ],
    "never_show_on_hud": ["internal_name_zh", "case id", "named formula", "textbook diagnosis"],
    "process": {
        "missing_exam_penalty": 0.12,
        "missing_primary_exam_extra": 0.08,
        "min_multiplier": 0.40,
        "formula": "process_mult = max(0.40, 1.0 - 0.12 * missing_count - 0.08 * missing_primary_count)",
    },
    "pattern_match": {
        "formula_path": {
            "required_cover_weight": 0.55,
            "preferred_cover_weight": 0.25,
            "nature_weight": 0.20,
            "required_cover": "unique actions in formula ∩ case.required_actions / len(required)",
            "preferred_cover": "unique actions ∩ preferred / max(1, len(preferred))",
            "nature_score": "fraction of herbs whose nature is in preferred_natures (slightly_* counts as its parent)",
            "legal_example_bonus": 0.08,
            "note": "hitting a legal_formula_example is a bonus, not a requirement. any set that covers required actions scores.",
        },
        "acupuncture_path": {
            "required_cover_weight": 0.60,
            "preferred_cover_weight": 0.25,
            "count_harmony_weight": 0.15,
            "ideal_point_count": [2, 5],
            "legal_example_bonus": 0.08,
        },
    },
    "speed": {
        "from": "mean onset of used herbs/points vs case.urgency",
        "map": {
            "fast_on_medium_or_high_urgency": "fast",
            "slow_on_low_urgency": "steady",
            "fast_on_low_urgency": "a_bit_rushed",
            "slow_on_medium_or_high": "slow",
        },
        "numeric": {"fast": 1.0, "steady": 0.85, "a_bit_rushed": 0.7, "slow": 0.55, "none": 0.2},
        "mod_on_final": 0.15,
        "formula": "final += 0.15 * (speed_numeric - 0.7)",
    },
    "mistreat": {
        "if_any_forbidden_action_in_treatment": True,
        "penalty": 0.35,
        "cap_rank_at": "slight",
        "flag": "mistreat",
    },
    "overtreat": {
        "if_sum_zheng_cost_gt_case_over_treat_zheng_cost": True,
        "if_over_treat_action_count_gte": 3,
        "if_herb_count_gt": 8,
        "if_point_count_gt": 5,
        "penalty": 0.12,
        "flag": "overtreat",
        "does_not_by_itself_make_mistreat": True,
    },
    "final": {
        "formula": "score = pattern * process_mult; score -= mistreat_penalty; score -= overtreat_penalty; score += speed_mod; clamp 0..1",
        "both_paths_can_reach_toward_heal": True,
        "two_legal_examples_per_path_must_both_reach_at_least_clear_if_all_exams_done": True,
    },
}

nature_parent = {
    "hot": "hot",
    "warm": "warm",
    "slightly_warm": "warm",
    "neutral": "neutral",
    "slightly_cold": "cold",
    "cool": "cold",
    "cold": "cold",
}

proficiency = {
    "enabled": False,
    "slice_note": "本期只留接口，不涨不耗不解锁。",
    "apprentice_level": 1,
    "xp": 0,
    "skills": {
        "wang": 0,
        "wen_listen": 0,
        "wen_ask": 0,
        "qie": 0,
        "formula": 0,
        "acupuncture": 0,
    },
    "hooks": {
        "on_exam_complete": "no-op this slice",
        "on_settlement": "no-op this slice",
        "future": "level gates extra herbs, pulse resolution, apprentice NPC",
    },
}

slice_logic = {
    **pack,
    "fsm": fsm,
    "herbs": herbs,
    "acupoints": acupoints,
    "cases": cases,
    "scoring": scoring,
    "nature_parent": nature_parent,
    "proficiency": proficiency,
    "contracts": {
        "script": "bind_character_id filled (char_porter / char_clerk / char_copyist); keep inquiry_anchor and never_say; do not add diagnosis names to player text",
        "art": "implement three pulse.visual profiles; formula plate is a drop target; points are on-body",
        "prototype": "load this json; do not replace drag/tap with OptionButton; Qwen uses inquiry_anchor + never_say; API fail uses inquiry_anchor as template lines",
    },
}

(out / "slice_logic.json").write_text(
    json.dumps(slice_logic, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)
print("wrote", out / "slice_logic.json", "bytes", (out / "slice_logic.json").stat().st_size)
